### ISSUE TITLE
Modificar el nombre de las columnas y reordenar los Issues

### ISSUE THREAD

**Issue by vcalzadaga** [CIFP-Jose-luis-Garci/Ascension#14]
En la pestaña Projects dentro de Proyectos de Juegos, debéis generar las columnas "To Do", "In Progress" y "Verify". No debéis organizarlas por temáticas como tenéis ahora. De esta forma cada nuevo issue o tema pendiente de hacer figurará  automáticamente en "To Do". Una vez que empecéis a trabajarlo y desarrollarlo lo pasaréis a "In Progress" para acabar en "Verify" cuando esté finalizado y cerrado

Por favor, realizad estos cambios

**Comment by Riko218** [comment]
Ya esta cambiado
