### ISSUE TITLE
Diseñar interfaz y hacer un listado de lo que vamos a necesitar en esa interfaz

### ISSUE THREAD

**Issue by Riko218** [CIFP-Jose-luis-Garci/Ascension#22]
Si necesitamos modelado 3d, imagenes, particulas texturas... cualquier cosa que se vaya a necesitar para la interfaz y los menus del juego.

**Comment by LauraLlamas** [comment]
![Captura](https://user-images.githubusercontent.com/72600964/104811519-60107b00-57fc-11eb-8878-56e52e73f36a.PNG)
Captura de un archivo de illustrator.

**Comment by LauraLlamas** [comment]
Pendiente de hacer más interface pero ya tenemos la estructura creada de como tiene que ser.

**Comment by alhgo** [comment]
Vamos a intentar ir metiendo ya escenas con los menús en el proyecto de Unity del repositorio (bien coordinados para que no haya conflictos), y así podemos dotarlas de interactividad y ver cómo quedan.
