### ISSUE TITLE
Buscar documentacion sobre base de datos en unity

### ISSUE THREAD

**Issue by Riko218** [CIFP-Jose-luis-Garci/Ascension#24]
Tenemos la duda de como hacer variables permanentes aun cerrando el videojuego. Te ha tocado buscar la informacion necesaria ;)

**Comment by alhgo** [comment]
Este issue llevaba tiempo pendiente. He visto que Unity tiene un método exclusivamente para guardar información localmente. Haré pruebas para ver si funciona: https://docs.unity3d.com/ScriptReference/PlayerPrefs.html
