### ISSUE TITLE
Como hacer que un personaje te persiga y cuando deje de verte no te persiga.

### ISSUE THREAD

**Issue by Riko218** [CIFP-Jose-luis-Garci/Ascension#25]
Como hacer que un personaje te persiga y cuando deje de verte no te persiga.
Y al salir de su visión deje de seguirte.
Al estar cerca que aumente un nivel de visión.
También habría que mirar, como hacer que ese personaje tenga cono de visión como si fuera una linterna y afecte los bloques a los que esta dando. Para simular la luz de la linterna.

**Comment by alhgo** [comment]
Que te persiga o no dependerá lógicamente de una booleana. Y esa nos la da directamente el "Raycasting" de Unity, que es como un "rayo" que sale desde un origen hacia un destino, y devuelve "true" si impacta: 

[Unity Docs](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html)

[Vídeo que explica cómo funciona](https://www.youtube.com/watch?v=EINgIoTG8D4)

Este método puede incluir la máxima distancia a la que se "dispara" ese rayo. Para saber a qué distancia está el GameObjecto usaríamos otros métodos.
