### ISSUE TITLE
Mecanica tercera persona a primera persona para puzzles o ciertos objetos.

### ISSUE THREAD

**Issue by Riko218** [CIFP-Jose-luis-Garci/Ascension#30]
Utilizar el cambio de camara de tercera a primera persona para entrar en conductos de ventilacion o para abrir cajones o algo asi. (Experimental)

**Comment by alhgo** [comment]
Os recomiendo el paquete de Cinemachine (creo que ya lo conocéis) yo he hecho pruebas para los de Moksha con una Free Look Camera, y funciona bien. Eso sí, tuve que crear dos ejes nuevos vinculados al stick derecho del mando para controlar la cámara en torno al personaje. Aquí está toda la documentación: https://docs.unity3d.com/Packages/com.unity.cinemachine@2.3/manual/index.html

**Comment by Riko218** [comment]
He estado probando durante mucho tiempo el cinemachine y no se porque se movía la cámara sola todo el rato, no he encontrado ninguna solución (ya que no debería ocurrirme) creo que es algún problema con lo que ya teníamos metido, así que he metido unos assets para el control de la cámara como si fuese tercera persona. Pero para pasar a primera por ahora vamos a descartarlo.

**Comment by alhgo** [comment]
Indicadme qué scripts intervienen, y en cuanto pueda sincronizar el repositorio, la escena que crearé para probar los checkpoint haré pruebas de pasar a 1ª persona también

**Comment by Riko218** [comment]
Este issue se creó cuando íbamos a implementar el cinemachine para la cámara pero se me movia ella sola y al final lo descarte por que no se realmente que fallaba y utilice al asset invector también, así que realmente no creo que se pueda incorporar esta idea.

**Comment by alhgo** [comment]
Ok. Pues issue totalmente cerrado, y ya veremos qué pasa con el Invector
