### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by LauraLlamas** [CIFP-Jose-luis-Garci/Ascension#37]
Hacer un contador de visión, si entras en rango de cámara y no sales a tiempo pierdes. Hacer que se vea visualmente también.

**Comment by alhgo** [comment]
Consejo: es muy habitual crear objetos "invisibles" en el escenario (con desactivarles el Mesh Renderer es suficiente), pero con colliders en modo trigger, de forma que cuando el personaje toca ese objeto se lanza un script. Es habitual para detectar cuándo un personaje entra en una zona.

Otra cosa, por si os interesa, este fin de semana intentaré hacer un vídeo sobre iluminación y postproducción, pero quizás os interese explorar los efectos que ofrece el paquete Post Processing Stack: https://www.youtube.com/watch?v=5cjhNjtkpVE&feature=emb_logo

**Comment by LauraLlamas** [comment]
He conseguido que al entrar en un área comience un contador que si terminas te cambia de escena, pierdes, pero si te sales para y se reinicia.

`private float moveSpeed = 3f;
    private float tiempoCamara = 5f;
    private bool dentro = false;
   
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        moverNave();
        if (dentro)
        {
            tiempoCamara -= Time.deltaTime;
            Debug.Log(tiempoCamara);
            if (tiempoCamara <= 0)
            {
                SceneManager.LoadScene("Escena2");
            }
        }
    }

    void moverNave()
    {
        float desplX = Input.GetAxis("Horizontal");
        float desplZ = Input.GetAxis("Vertical");
        transform.Translate(Vector3.forward * Time.deltaTime * moveSpeed * desplZ);
        transform.Translate(Vector3.right * Time.deltaTime * moveSpeed * desplX);
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.tag == "Camara")
        {
            Debug.Log("Dentro");
            dentro = true;
            
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.gameObject.tag == "Camara")
        {
            Debug.Log("Fuera");
            dentro = false;
            tiempoCamara = 5f;
        }
    }`

**Comment by LauraLlamas** [comment]
He conseguido que al entrar en un área comience un contador que si terminas te cambia de escena, pierdes, pero si te sales para y se reinicia.
``private float moveSpeed = 3f;
    private float tiempoCamara = 5f;
    private bool dentro = false;
   
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        moverNave();
        if (dentro)
        {
            tiempoCamara -= Time.deltaTime;
            Debug.Log(tiempoCamara);
            if (tiempoCamara <= 0)
            {
                SceneManager.LoadScene("Escena2");
            }
        }
    }

    void moverNave()
    {
        float desplX = Input.GetAxis("Horizontal");
        float desplZ = Input.GetAxis("Vertical");
        transform.Translate(Vector3.forward * Time.deltaTime * moveSpeed * desplZ);
        transform.Translate(Vector3.right * Time.deltaTime * moveSpeed * desplX);
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.tag == "Camara")
        {
            Debug.Log("Dentro");
            dentro = true;
            
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.gameObject.tag == "Camara")
        {
            Debug.Log("Fuera");
            dentro = false;
            tiempoCamara = 5f;
        }
    }

**Comment by LauraLlamas** [comment]
Hacer un marcador visible para avisar al jugador de cuanto tiempo le queda antes de que le pillen.

**Comment by LauraLlamas** [comment]
Hacer logos tarjetas cuando la coges
