### ISSUE TITLE
Sistema de checkpoints

### ISSUE THREAD

**Issue by ghost** [CIFP-Jose-luis-Garci/Ascension#47]

**Comment by alhgo** [comment]
¿Alguna descripción del issue que me ayude a comprender qué hay que hacer exactamente? :)

**Comment by Riko218** [comment]
Se necesitan unos 3 checkpoint o más para que cuando pases de zona no puedas volver atrás si te pillan los guardias. Y así no comerte el nivel por completo.

**Comment by alhgo** [comment]
Me he ido a poner con ello, y me ha dado problema GitHub para sincronizar el repositorio. Problemas de branches dice (aunque yo no veo más de uno) y de nombres muuuuy largos. A alguien más le pasa?

**Comment by Riko218** [comment]
Acabo de hacer un pull origin y se ha actualizado correctamente al menos en mi pc. No se que puede ser.

**Comment by alhgo** [comment]
Ok, lo clono de nuevo a ver qué tal. Os cuento a lo largo de la mañana.

**Comment by alhgo** [comment]
Parece que era de mi Github, porque me da el mismo error con los demás proyectos. Lo he clonado de nuevo en otra ubicación de mi PC y funciona.
He subido una escena de prueba para que veáis cómo podrían funcionar los Checkpoints mediante un array de GameObjects (los emptyObjects que indican la posición del checkpoint).
Para probarla, al lanzar el juego seleccionar el Parent con los Checkpoints y activar los gizmos, de esa forma veréis dónde están. Al dar a la barra espaciadora, simulará que ha muerto y mediante el método Invoke al cabo de 2 segundos os devuelve al último punto de control. A ver si os sirve.

**Comment by Riko218** [comment]
Vale si funciona perfectamente con nuestro personaje añadiéndole el script y quitándole lo de mover personaje. La cámara también se mueve a el personaje al teletransportarlo. Gracias lo único que veo que falla que tendrá que ser algo del collider es que al aparecer aparece justo encima del checkpoint supongo que si se introduce dentro del suelo y se queda solo la parte de arriba encima del suelo debería funcionar perfectamente.

**Comment by alhgo** [comment]
Efectivamente, lo "teletransporta" a las coordenadas del Empty Object, que dependerán de su punto de anclaje y el del personaje. Como todos están metidos en un Parent, es muy fácil subirlos o bajarlos para que coincidan en altura.

**Comment by Riko218** [comment]
Solo queda implementarlas en el mapa real. cierro
