### ISSUE TITLE
Como añadir unas animaciones a las que ya hay creadas del invector assets

### ISSUE THREAD

**Issue by Riko218** [CIFP-Jose-luis-Garci/Ascension#51]
Queremos añadir nuevas animaciones al animator que ya tenemos.

**Comment by alhgo** [comment]
Si disponemos de esa animación, es arrastrarla al Animator Controller y listo. Yo lo he hecho, por ejemplo subiendo un rigg a Mixamo y descargando el fbx con la animación incorporada, que luego arrastraba directamente al Panel

**Comment by Riko218** [comment]
si pero, en la versión actual del plugin invector del personaje SI podemos añadírselas mas fácilmente, el otro plugin invector Lite que utilizaba, estaban capadas por script y no se podían añadir nuevas animaciones. No conseguías hacer que las hiciera el personaje. Por eso digo lo del invector. Esta versión tiene zona especifica para añadir animaciones y asociarlas a el script cosa que la otra versión NO y eso es lo que quería comprobar (Que aun tengo que hacerlo.) Se que si añades animaciones de mixamo a un animator y cambias el rig a humanoid si funciona. Algunas hay que tocar la transform position de la animación (mas o menos era así no me acuerdo bien de memoria, si lo veo si se donde se toca)

**Comment by alhgo** [comment]
Ok, vale, no contaba con el plugin. Tendría que hacer pruebas, pero al ser un plugin de pago es lógico que esté limitado. ¿Correcto?

**Comment by Riko218** [comment]
El invector es de pago pero lo he conseguido "pagando" ;) y esta versión si se puede añadir, el Lite era el que estaba bloqueado.

**Comment by Riko218** [comment]
El invector es de pago pero lo he conseguido "pagando" ;) y esta versión si se puede añadir, el Lite era el que estaba bloqueado.

**Comment by alhgo** [comment]
Jajajja, vale. No contaba con eso. Pues ahí tengo que reconocer que no sé cómo funciona. Pero todo es investigar. ¿Es muy importante la animación que queremos añadir? Porque si no, podemos dejarlo para más adelante y priorizar otras cosas. Lo que me digáis.

**Comment by Riko218** [comment]
por ahora no es importante era solo para diseñar el mapeado pero por ahora descartamos estas opciones, por ahora.
