### ISSUE TITLE
Derechos

### ISSUE THREAD

**Issue by LauraLlamas** [CIFP-Jose-luis-Garci/Ascension#6]

**Comment by Riko218** [comment]
Buscare información de estos temas
Montar Una SL
Registrar una Marca, nombre y logo: ¿precio?
Gestoría que lleve nuestra empresa

Creo que en tema de derechos no seria necesario nada mas

**Comment by Riko218** [comment]
Montar Una SL 3.000€ ingresados necesarios para poder empezar la SL, y los gastos rondan entre 600 y 900€ Vamos a utilizar el gasto de: 900€

Registrar una Marca, nombre y logo: 156,09 + 96€ si se registra el nombre y logo del videojuego.

Gestoría que lleva los papeleos y las cuentas de la empresa aproximadamente: 70/80€

Fuente información SL: https://cutt.ly/VhmEwGT
Fuente información Marca y logotipo: https://cutt.ly/ohmEHrm
