### ISSUE TITLE
Equipo técnico

### ISSUE THREAD

**Issue by LauraLlamas** [CIFP-Jose-luis-Garci/Ascension#7]

**Comment by Riko218** [comment]
Voy a desarrollar el equipo tecnico:
Partiendo de que vamos a ser 8 personas en el proyecto con estos oficios:

2 programadores 
2 artistas (Uno de concepts  y marketing y otro de diseño de niveles.
1 diseñador de producto
1 RP/Buscador de producción
1 Diseñador de Juego
1 Compositor Musical

**Comment by Riko218** [comment]
Dos programadores: 
El salario de un programador en el 2020 con menor experiencia oscila entre los 16.000 y los 22.000 euros, siendo la media unos 18.000 euros al año.

Dos artistas:
Uno de concepts y marketing 25.881 € / año
Otro de diseño de niveles / Level designer: 36.214 € / año

Diseñador de product / Average Product Designer 35,412 € / año

Productor Lider / Product Lead 40.000€ / año

Un Diseñador de Juego / Game designer 31.061 € / año

Un Compositor Musical / Compositor designer Salario mínimo y máximo de un Músicos, cantantes y compositores - de 765,07 € a 3.828,82 € por mes. Nosotros le pagaremos anualmente 24.000€


Fuentes:
http://hackaboss.com
http://payscale.com
http://tusalario.es
http://glassdoor.es
