### ISSUE TITLE
Material técnico

### ISSUE THREAD

**Issue by LauraLlamas** [CIFP-Jose-luis-Garci/Ascension#9]

**Comment by Riko218** [comment]
Para el material técnico he decidido poner las necesidades de cada profesional y las necesidades de la conformidad de la oficina. Junto con los gastos que se pueden generar mensualmente.

**Gastos:**
**Eléctricos:**
Para calcular los gastos de luz: He calculado la potencia máxima que podría haber en la oficina según el consumo de cada aparato electrónico e iluminación.
Tendremos Valores aproximados de:
750w por ordenador + periféricos y SAIS. Total: 6 Kw/h
250w por impresora + escáner. Total: 0,25 Kw/h
2000w para un servidor con un splitter de 10 unidades. 2 Kw/h
Un consumo de 700w para toda la iluminación de la oficina. 0,7 Kw/h
150 w de consumo del agua de AquaService. 0,15 Kw/h
Y un consumo aproximado de 300w entre nevera y microondas. 0,3 Kw/h
Total: 9,4 Kw/h x 10h de uso = 94Kw x Día
94 x 22 Dias laborales = 2.068 Kw/Mensuales
2.068 x 12 meses = 24.816 Kw/Anuales
24.816 Kw x 0.14 cent = 3.474,24€ aproximados anuales en factura de la luz.
Tarifa 2.1 A 5-10 Kw 
https://www.naturgy.es/empresas/electricidad_o_gas/contratar_electricidad_o_gas/recomendador_empresas/plan_negocio_ahorro_21a

**Agua:**
Según los estudios publicados por la OMS en esta web:
https://www.actualidadambiental.pe/debemos-consumir-100-litros-de-agua-al-dia-por-persona-pero-consumimos-hasta-250-litros/#:~:text=De%20acuerdo%20con%20la%20Organizaci%C3%B3n,de%20consumo%20como%20de%20higiene

Se gastan 100 L diariamente por persona. Contando que una persona este 1/3 de su día en el trabajo, se gastaran 33L de agua por persona diarios aproximadamente. Tenemos 8 personas trabajando en el Proyecto así que concluimos que se gastarán 264 Litros de agua diarios en la oficina. Multiplicamos por 22 días laborales y nos da 5.808 L mensuales. Que al multiplicar por los 12 meses anuales son: 69.696 Litros de agua. El litro de agua tiene un precio aquí en Madrid bastante bajo así que estaríamos hablando de 1,89€* por cada 1000L. Nos da que pagaríamos 131€ al año, pero con impuestos se quedarían unos 200/250 € al año de gasto aproximado.

*Para el calculo hemos utilizado la media española encontrada en esta web:
https://www.europapress.es/madrid/noticia-canal-isabel-ii-mantiene-congelado-precio-agua-quinto-ano-consecutivo-20200131094006.html#:~:text=El%20Canal%20de%20Isabel%20II%20destaca%20tambi%C3%A9n%20que%20el%20precio,est%C3%A1%20en%201%2C84%20euros

Para el agua de consumo fría y caliente para té, hemos decidido colocar una empresa que se encargue de ello. A través de AquaService conseguimos 3 garrafas de 20L de agua por 29€ + Iva al mes, con un año de permanencia. Que al ser un producto de necesidad tiene un iva del 10% conque pagaríamos al mes 31,90€ x 12 mensualidades = 384€ anuales de agua embotellada.

Web: https://www.aquaservice.com/) (Información cedida a través de llamada telefónica

**Internet:**
Para contratar el internet hasta el servidor nos hemos decantado entre las ofertas por Movistar, por ser una de las empresas más seguras en cuestión de fiabilidad y estabilidad de la fibra. A través de su pagina web para empresas hemos conseguido una oferta de Fusión Empresas por 51€ al mes sin impuestos, con impuestos 61,71€ mensuales. Que se queda en: 740,52 € Anuales
Web: https://www.movistar.es/empresas/portada/fusion/

**Instalación de redes y mantenimiento del servidor:**
Al no encontrar una empresa que nos enviara el presupuesto, lo he realizado yo mismo buscando los materiales aproximados. Se prevé instalación para futuros proyectos.

https://www.tpainformatica.com / http://www.pccomponentes.es / https://www.it-market.com

**Armario Servidor** 216€: https://www.pccomponentes.com/armario-rack-19-32u-600x800
**Switch para conexión de ordenadores** 127,60€: https://cutt.ly/KhmntdU
**Fuente de alimentación** 1037,76€: https://cutt.ly/phmniq4
**NAS de discos duros** 261€: https://cutt.ly/1hmnjVY
**Bobina de cable de 300m** 69,99€: https://cutt.ly/whmnxDs
**Disco duro 1Tb x 10 unidades** 34,94€ x10 = 349,4€ https://cutt.ly/7hmnmC1
**Instalación y configuración de equipos:** 500€
**Mantenimiento:** 80€ mensuales x 960€ anuales.


**Material Técnico y necesidades:** 
**Ordenadores PcCom:** 926,04€ x 8 = 7.408,32 https://cutt.ly/HhmnB1O
**SAIS:** 62,99€ x 8 = 503,92€ https://cutt.ly/5hmnMuH
**Teclado y ratón:** 78,99€ x 8 = 631,92 € https://cutt.ly/3hmn3s0
**Tv:** 519,01€ https://cutt.ly/khmn7oZ
**Monitor:** 118,99€ x 8 = 951,92 https://cutt.ly/qhmn5EG
**Mando Xbox One:** 64,95€ x 4 = 259,8€ https://cutt.ly/zhmmw2W
**Regleta:** 19,95€ x 10 = 199,5€ https://cutt.ly/4hmmi52
**Teléfono fijo:** 60,51€ https://cutt.ly/4hmmsXD
**Teclado musical:** 194€ https://cutt.ly/mhmmfXy
**Micrófono profesional:** 436€ https://cutt.ly/qhmmjRt
**Procesador de efectos:** 70,38€ https://cutt.ly/Yhmmk74
**Tableta gráfica:** 399,99 € x 2 = 799,98 € https://cutt.ly/JhmmxW9
**Paquete de folios:** 4,40 € x 5 = 22€ https://cutt.ly/rhmmnQG
**Impresora Brother:** 304,08€ https://cutt.ly/ghmmmAb
**Escáner:** 306,22€ https://cutt.ly/OhmmQ16
**Nevera:** 219€ 
https://www.mediamarkt.es/es/product/_frigor%C3%ADfico-dos-puertas-teka-ftm-240-207-l-descongelaci%C3%B3n-autom%C3%A1tica-4-bandejas-de-cristal-clase-a-1336636.html
**Vasos:** 3€ x 2 = 6€ https://cutt.ly/whmmU7R
**Cubiertos:** 5€ x 2 = 10€ https://cutt.ly/XhmmDtR
**Microondas:** 84,91€ https://cutt.ly/0hmmJ6j
**Cafetera:** 46,99€ https://www.mediamarkt.es/es/product/_cafetera-de-c%C3%A1psulas-krups-piccolo-kp-100-bsc-antracita-15-bar-0-6-l-1-500-w-antracita-1477321.html
